# Generated by Django 4.0.3 on 2022-04-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_questions_options_questions_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='likes',
        ),
    ]
