# Generated by Django 4.0.3 on 2022-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_answers_likes_remove_questions_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='fullname',
        ),
    ]
