# Generated by Django 4.0.3 on 2022-04-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_questions_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
