# Generated by Django 4.0.3 on 2022-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gen',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
