# Generated by Django 4.0.3 on 2022-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userprofile_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
