# Generated by Django 4.0.3 on 2022-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userprofile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='PTPTgroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
